### ISSUE TITLE
Changing monitor settings using wlr-randr causes a black screen and no output

### ISSUE THREAD

**Issue by johanengstrand** [engstrand-config/dwl-guile#19]

**Comment by johanengstrand** [comment]
`dwl-guile` does not seem to respect refresh rates above 60 Hz that I set under `#:monitor` for my current system `p400s`. The command `wlr-randr --output DP-1 --custom-mode 2560x1440@120` should set the refresh rate to 120 Hz, but instead causes a black screen and no output.

Everything seems to work fine in Sway.

**Comment by Frewacom** [comment]
I broke the monitor-config patch in the latest update, hence why your settings does not work. As for wlr-randr, this seems to be an issue in upstream dwl as well.

**Comment by Frewacom** [comment]
Should hopefully work like before as of [v1.3.1](https://github.com/engstrand-config/dwl-guile/releases/tag/v1.3.1).
