### ISSUE TITLE
xkb dont working

### ISSUE THREAD

**Issue by AnYurii** [engstrand-config/dwl-guile#38]
Hi, 
I cant change keyboard layout.
Its the config of xkb:
`(set-xkb-rules
     '((model . "pc104")
       (layout . "us,ru")
       (variant . ",nodeadkeys")
       (options . "grp:shift_caps_toggle")))`

setxkbmap dont working to.

I installed xkeyboard-config and libinput, but without results.

On sway all working fine

**Comment by Frewacom** [comment]
This is definitely a bug. I'll have a look, thanks!

**Comment by ReilySiegel** [comment]
Has there been any progress on this issue?

**Comment by Frewacom** [comment]
Hi, sorry for the delay.

This should be fixed in [v2.0.2](https://github.com/engstrand-config/dwl-guile/releases/tag/v2.0.2). The home service has also been updated to use the latest version. 

Let me know if everything works as expected.

**Comment by ReilySiegel** [comment]
@Frewacom, thanks for the quick reply! This resolves the issue.
