### ISSUE TITLE
Invoke startup hook just once

### ISSUE THREAD

**Issue by migalmoreno** [engstrand-config/dwl-guile#39]
I use the `dwl:hook-startup` in [my configuration](https://github.com/migalmoreno/guix-config/blob/master/src/dotfiles/users/vega.scm#L968) to manually start the Shepherd daemon so that home services like `kanshi` are initialized after the compositor. However, doing this causes the `dwl-guile` daemon to break upon reconfiguration. My first thought was to get the PID, persist it in a variable and check if this exists in further reconfigurations, but I'm not sure how to go about this via `dwl:spawn`. AFAICT, you work around this in your config by using custom Shepherd services that have a `requirement` of `dwl-guile`, but tackling this would be useful for people that don't use RDE/don't want to override features.

**Comment by Frewacom** [comment]
Hi,

The startup hook is only called once during startup, and will not be called again, even if you reload the config (from what I can see). 

Are you sure that your startup hook callbacks are called again on reconfigure?

**Comment by migalmoreno** [comment]
Yes, my bad, apologies. It seems that using a `program-file` inside the callback caused some weird quirks. I've now reworked it to use `dwl:spawn` and it works as expected.

**Comment by Frewacom** [comment]
No worries!
