### ISSUE TITLE
Failing on set monocle layout.

### ISSUE THREAD

**Issue by lidgnulinux** [engstrand-config/dwl-guile#41]
Hello, nice compositor. Today I'm trying it and found something that bother me, I can't set / use monocle layout (both via keybind or via `dwl-guile -e`).

I have this on my init.scm

```
(set-keys "s-d" '(dwl:spawn "wofi")

;;; other keybindings

          "s-m" 'dwl:monocle
)
```

I also run : 

```
$ dwl-guile -e "(dwl:monocle)"
```

The output I got : 

```
Wrong number of arguments to #<procedure dwl:monocle (_)>
```

Any clue to fix it ? Thanks.

**Comment by Frewacom** [comment]
Hi,

The `dwl:monocle` procecure should not be called directly, since it requires a reference to the monitor it should arrange. Instead, do something like this:

```lisp
;; From the man pages. Add the monocle layout to the list of enabled layouts.
(set-layouts 'monocle "|M|" 'dwl:monocle)

;; dwl:set-layout accepts the name of the enabled layout as a string.
;; The default layout (tile) is named "default". 
(set-keys "s-m" '(dwl:set-layout "monocle"))
```

I have also updated the man page to include an example of this.

**Comment by lidgnulinux** [comment]
Thanks @Frewacom
